import type { Metadata } from "next";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import { GMProvider } from "../(utils)/context/GMContext";
import HamburgerMenu from "@/components/user/MenuBar";
import AuthRoute from "@/components/user/AuthRoute";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserPanelLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthRoute>
      <div className="flex">
        <HamburgerMenu />
        {children}
        <Toaster richColors />
      </div>
    </AuthRoute>
  );
}
