import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";
import HamburgerMenu from "@/components/user/MenuBar";
import AuthRoute from "@/components/user/AuthRoute";
import { cn } from "@/lib/utils";
import BottomMenu from "@/components/web/BottomMenu";

const fontInter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserPanelLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthRoute>
      <div className={cn("flex", fontInter.className)}>
        <HamburgerMenu />
        {children}
        <BottomMenu />
      </div>
    </AuthRoute>
  );
}
