version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: goodmart
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: goodmart_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
