import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/web/Navbar";
import React from "react";
import BottomMenu from "@/components/web/BottomMenu";

export const metadata: Metadata = {
  title: "GOODMART",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="">
      <Navbar />
      {children}
      <BottomMenu />
    </div>
  );
}
