import type { Metadata } from "next";
import "../globals.css";
import { Inter as FontSans, Carter_One } from "next/font/google";
import Navbar from "@/components/web/Navbar";
import React from "react";

const fontSans = FontSans({
  subsets: ["latin"],
  display: "swap",
});

const carterOne = Carter_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-carter-one",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${fontSans.className} ${carterOne.variable}`}>
      <Navbar />
      {children}
    </div>
  );
}
