import type { Metadata } from "next";
import "../globals.css";
import { Inter as FontSans } from "next/font/google";
import Navbar from "@/components/web/Navbar";
import { GMProvider } from "../(utils)/context/GMContext";

const fontSans = FontSans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
