import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans, Carter_One } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { GMProvider } from "./(utils)/context/GMContext";
import { NextUIProvider } from "@nextui-org/system";
import PopupManager from "@/components/web/popup";

const fontSans = FontSans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const carterOne = Carter_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-carter-one",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-inter antialiased pb-24 lg:pb-0",
          fontSans.variable,
          carterOne.variable
        )}
      >
        <NextUIProvider>
          <GMProvider>
            {children}
            <PopupManager />
          </GMProvider>
          <Toaster richColors expand={true} />
        </NextUIProvider>
      </body>
    </html>
  );
}
