# Generated by Django 5.0.6 on 2024-12-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
