# Generated by Django 5.0.6 on 2024-12-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_coupon_description_coupon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='passcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
