# Generated by Django 5.0.6 on 2024-07-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_user_aadhar_alter_user_aadhar_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
