# Generated by Django 5.0.6 on 2024-07-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Product Vendor', 'Product Vendor'), ('Service Vendor', 'Service Vendor')], max_length=20, null=True),
        ),
    ]
