# Generated by Django 5.0.6 on 2024-08-10 15:03

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_brand_id_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.vendor_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=mainapp.models.vendor_directory_path),
        ),
    ]
