# Generated by Django 5.0.6 on 2024-08-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_product_image_alter_product_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_specifications',
            old_name='specification',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='product_image',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='product_image',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product_specifications',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='product_specifications',
            name='status',
        ),
        migrations.AlterField(
            model_name='product',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modify_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
