# Generated by Django 5.0.6 on 2024-07-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_user_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
