# Generated by Django 5.0.6 on 2025-01-20 17:18

import django.db.models.deletion
import mainapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_user_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photograph', models.ImageField(blank=True, null=True, upload_to=mainapp.models.user_directory_path)),
                ('dob', models.DateField(blank=True, null=True)),
                ('passbook_image', models.ImageField(blank=True, null=True, upload_to=mainapp.models.user_directory_path)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=15, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
