# Generated by Django 5.0.6 on 2025-01-21 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='mainapp.address'),
        ),
    ]
