# Generated by Django 5.0.6 on 2025-01-29 14:59

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_user_detail_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='type',
            field=models.CharField(blank=True, choices=[('Quantity', 'Quantity'), ('Size', 'Size'), ('Color', 'Color'), ('Weight', 'Weight'), ('Material', 'Material')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='passbook_image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.user_detail_directory_path),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.user_detail_directory_path),
        ),
    ]
