# Generated by Django 5.0.6 on 2024-07-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('point', models.IntegerField(blank=True, default=1, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('attr1', models.CharField(blank=True, max_length=100, null=True)),
                ('attr2', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('item_type', models.IntegerField(blank=True, null=True)),
                ('image3', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(blank=True, null=True)),
                ('modify_on', models.DateTimeField(auto_now=True)),
                ('modify_by', models.IntegerField(blank=True, null=True)),
                ('product_added_type', models.IntegerField(blank=True, default=1, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('target', models.CharField(blank=True, default='repurchase', max_length=100, null=True)),
                ('capping', models.IntegerField(blank=True, null=True)),
                ('ratio', models.IntegerField(blank=True, null=True)),
                ('pairs', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
