# Generated by Django 5.0.6 on 2024-09-08 12:21

import django.db.models.deletion
import mainapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aadhar_certificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aadhar_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='father',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pan_certificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pan_verified',
        ),
        migrations.CreateModel(
            name='Vendor_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('photograph', models.ImageField(blank=True, null=True, upload_to=mainapp.models.vendor_directory_path)),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_certificate', models.ImageField(blank=True, null=True, upload_to=mainapp.models.vendor_directory_path)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_certificate', models.ImageField(blank=True, null=True, upload_to=mainapp.models.vendor_directory_path)),
                ('aadhar', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_certificate', models.ImageField(blank=True, null=True, upload_to=mainapp.models.vendor_directory_path)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
