# Generated by Django 5.0.6 on 2025-01-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_homepagebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebanner',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
