# Generated by Django 5.0.6 on 2025-02-01 19:19

import django.db.models.deletion
import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_homepagebanner_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Top Deals', 'Top Deals'), ('Recommended for You', 'Recommended for You'), ('Featured Items', 'Featured Items'), ('Shop by Category', 'Shop by Category'), ('New Arrivals', 'New Arrivals'), ('Trending Products', 'Trending Products')], max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(help_text='Order in which the section appears')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('product', 'Product'), ('category', 'Category')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mainapp.models.web_direcory_path)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modify_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product_category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainapp.homepagesection')),
            ],
        ),
    ]
