# Generated by Django 5.0.6 on 2024-09-08 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_address_alter_vendor_detail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_detail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
