# Generated by Django 5.0.6 on 2025-02-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_homepagesection_homepageitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageitem',
            name='content_type',
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='content_type',
            field=models.CharField(choices=[('Product', 'Product'), ('Category', 'Category')], max_length=10, null=True),
        ),
    ]
