# Generated by Django 5.0.6 on 2024-09-10 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_vendor_detail_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_detail',
            old_name='firm_name',
            new_name='firm',
        ),
        migrations.AddField(
            model_name='address',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor_detail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_detail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
