# Generated by Django 5.0.6 on 2025-02-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_homepageitem_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('Terms and Conditions', 'Terms and Conditions'), ('Return Policy', 'Return Policy'), ('Product Warranty', 'Product Warranty'), ('Out Mission and Vision', 'Our Mission and Vision')], max_length=25, unique=True)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
