# Generated by Django 5.0.6 on 2025-02-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('Terms and Conditions', 'Terms and Conditions'), ('Return Policy', 'Return Policy'), ('Product Warranty', 'Product Warranty'), ('Our Mission and Vision', 'Our Mission and Vision')], max_length=25, unique=True),
        ),
    ]
