# Generated by Django 5.0.6 on 2024-09-10 13:17

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_vendor_detail_added_on_vendor_detail_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_detail',
            old_name='aadhar_certificate',
            new_name='aadhar_back_image',
        ),
        migrations.AddField(
            model_name='vendor_detail',
            name='aadhar_front_image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.vendor_directory_path),
        ),
    ]
