# Generated by Django 5.0.6 on 2025-02-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_product_purchase_amount_alter_policy_policy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageitem',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product_brand'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='content_type',
            field=models.CharField(choices=[('Product', 'Product'), ('Category', 'Category'), ('Brand', 'Brand')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='name',
            field=models.CharField(choices=[('Top Deals', 'Top Deals'), ('Recommended for You', 'Recommended for You'), ('Featured Items', 'Featured Items'), ('Shop by Brand', 'Shop by Brand'), ('New Arrivals', 'New Arrivals'), ('Trending Products', 'Trending Products')], max_length=100, unique=True),
        ),
    ]
