# Generated by Django 5.0.6 on 2024-09-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_rename_aadhar_certificate_vendor_detail_aadhar_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_detail',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor_detail',
            name='status_message',
            field=models.CharField(blank=True, default='Status is in Pending State', max_length=100, null=True),
        ),
    ]
