# Generated by Django 5.0.6 on 2024-09-26 06:41

import django.db.models.deletion
import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_points', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=mainapp.models.vendor_directory_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=mainapp.models.vendor_directory_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=mainapp.models.vendor_directory_path)),
                ('status', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_on', models.DateTimeField(auto_now=True, null=True)),
                ('modify_by', models.IntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.address')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='mainapp.vendor_detail')),
            ],
        ),
    ]
