# Generated by Django 5.0.6 on 2024-09-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_setting_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points',
            new_name='Coupon',
        ),
    ]
