# Generated by Django 5.0.6 on 2025-04-01 12:20

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_policy_policy_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Home Page', 'Home Page'), ('Category', 'Category'), ('Brand', 'Brand'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Wallet', 'Wallet'), ('Login', 'Login')], max_length=15, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mainapp.models.web_direcory_path)),
                ('text', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
