# Generated by Django 5.0.6 on 2024-09-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_address_co_ordinates_product_company_id_product_hsn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
