# Generated by Django 5.0.6 on 2024-10-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_user_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_detail',
            name='business_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
