# Generated by Django 5.0.6 on 2025-04-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_popup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popup',
            old_name='link',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='popup',
            old_name='is_enabled',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='text',
        ),
        migrations.AddField(
            model_name='popup',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='button_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
