# Generated by Django 5.0.6 on 2025-04-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_rename_link_popup_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
