# Generated by Django 5.0.6 on 2025-04-14 18:45

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_popup_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, choices=[('Home Page', 'Home Page'), ('Category', 'Category'), ('Brand', 'Brand'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Wallet', 'Wallet'), ('Login', 'Login')], max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mainapp.models.web_direcory_path)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
