# Generated by Django 5.0.6 on 2024-10-20 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_product_barcode_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='Product_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('Size', 'Size'), ('Color', 'Color'), ('Weight', 'Weight'), ('Material', 'Material')], max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_on', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='mainapp.product')),
            ],
        ),
    ]
