# Generated by Django 5.0.6 on 2024-11-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_detail',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
