# Generated by Django 5.0.6 on 2024-11-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_remove_order_payment_id_remove_order_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
    ]
