# Generated by Django 5.0.6 on 2024-11-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_product_category_views_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='border',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product_category',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
