from django.urls import path
from . import views

urlpatterns = [
    path("", views.index),
    path("registerUser/", views.registerUser),
    path("getUserInfo/", views.getUserInfo),
    path("sendVerificationEmail/", views.sendVerificationEmail),
    path('verify-email/<uidb64>/<token>/', views.verify_email, name='verify-email'),
    path('getProductCategory/', views.getProductCategory),
    path('getProductBrand/', views.getProductBrand),
    path('getSearchProducts/<str:search>/<str:category>/', views.getSearchProducts),
    path('getProduct/<int:id>/', views.getProduct),
    path('addToCart/', views.addToCart),
    path('getCart/', views.getCart),
    path('removeFromCart/', views.remove_cart),
    path('removeCart/', views.remove_all_cart),
    path('getCartCount/', views.get_cart_count),
    path('getUserAddress/', views.getUserAddress),
    path('addUserAddress/', views.addUserAddress),
    path('getAddress/<int:id>/', views.getAddress),
    path('getBillingDetails/', views.getBillingDetails),
    path('placeOrder/', views.createOrder),
    path('getOrderDetails/<int:id>/', views.getOrderDetails),
    path('placeOrder/<int:id>/', views.placeOrder),
    path('getOrders/', views.getOrders),
    path('getOrder/<int:id>/', views.getOrder),
    path('getFeaturedCategory/', views.getFearuredCategory),
    path('getParentCategory/', views.getParentCategory),
    path('getSubCategory/<int:id>/', views.getSubCategory),
    path('getCoupon/', views.getCoupon),
    path('redeemCoupon/', views.redeemCoupon),
    path('getWallet/', views.getWallet),
    path('createWallet/', views.createWallet),
    path('verifyPasscode/', views.verifyWalletPasscode),
    path('getShops/', views.getShops),
    path('addReferral/', views.addReferral),
]
