import type { Metadata } from "next";
import "../globals.css";
import { Inter as FontSans } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/admin/Sidebar";
import Header from "@/components/admin/Header";
import { GMAdminProvider } from "../(utils)/context/GMAdminContext";
import AdminRoute from "@/components/admin/AdminRoute";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GMAdminProvider>
      <AdminRoute>
        <div className="flex">
          <Sidebar />
          <div className="w-full">
            <Header />
            {children}
          </div>
        </div>
      </AdminRoute>
    </GMAdminProvider>
  );
}
