name: CI/CD for GoodMart

on:
  push:
    branches:
      - master # Trigger deployment on changes to the 'main' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment for Django (backend)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      # Set up Node.js environment for Next.js (frontend)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Deploy to the server
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/goodmart

            # Pull the latest changes
            git pull origin master

            # Install backend dependencies (if necessary)
            cd backend
            pip install -r requirements.txt

            # Install frontend dependencies (if necessary)
            cd frontend
            npm install

            # Build frontend (Next.js)
            npm run build

            # Restart backend (Gunicorn)
            pkill -f gunicorn
            gunicorn --bind 0.0.0.0:8000 goodmart.wsgi:application &

            # Restart frontend (Next.js)
            pkill -f next
            npm run start &

            # Restart Nginx to apply changes
            sudo systemctl restart nginx
