name: CI/CD for GoodMart

on:
  push:
    branches:
      - master # Trigger deployment on changes to the 'main' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Django virtual environment and install dependencies
        run: |
          cd backend
          python3 -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install Django dependencies
          python3 manage.py makemigrations
          python3 manage.py migrate

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install  # Install Next.js dependencies

      - name: Configure Git
        run: |
          git config --global user.name "CI/CD Bot"
          git config --global user.email "bot@gmail.com"

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }} # Server IP or hostname
          username: ${{ secrets.DEPLOY_USER }} # SSH username
          key: ${{ secrets.DEPLOY_KEY }} # SSH private key secret
          script: |
            cd /home/goodmart/goodmart

            git pull origin master
            git fetch origin master
            git merge --no-ff --no-edit HEAD

            cd backend
            python3 -m venv venv  # Create the virtual environment if not already there
            source venv/bin/activate  # Activate virtual environment
            pip install --upgrade pip  # Upgrade pip
            pip install -r requirements.txt  # Install or update backend dependencies
            python3 manage.py makemigrations
            python3 manage.py migrate
            deactivate  # Deactivate the virtual environment

            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            cd ..  # Move back to the root directory

            cd frontend
            npm install  # Install or update frontend dependencies

            npm run build  # Build the Next.js app for production

            # Restart the gunicorn service for Django
            sudo systemctl restart gunicorn

            # Restart the pm2 service for Next.js (ensure pm2 is installed and running)
            pm2 restart next  # Restart PM2 process for Next.js

            sudo systemctl restart nginx
